spring.config.import=file:.env[.properties]
logging.level.org.springframework.security=DEBUG
cors.allowed-origins=http://localhost:3000,http://localhost:8080,http://localhost:4200
spring.jpa.hibernate.ddl-auto=create-drop


# Database Init tables
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
